name: Sync Docs as Code - Confluence
on:
  push:
    branches:
        - main
    paths:
      - 'docs/**'
jobs:
  docs-as-code:
    runs-on: ubuntu-latest
    name: Sync Docs as Code - Confluence
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sync Docs as Code - Confluence
        uses: Bhacaz/docs-as-code-confluence@main
        with:
          folder: docs
          username: jfbastien@petalmd.com
          password: ${{ secrets.PASSWORD }}
          confluence-base-url: https://petalmd.atlassian.net/wiki
          space-id: ~661332374
          parent-page-id: 1028915542