name: Sync Docs as Code - Confluence
on:
  push:
    branches:
        - main
    paths:
      - 'docs/**'
jobs:
  docs-as-code:
    runs-on: ubuntu-latest
    name: Sync Docs as Code - Confluence
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Sync Docs as Code - Confluence
        uses: Bhacaz/docs-as-code-confluence@main
        with:
          folder: docs
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          confluence-base-url: ${{ secrets.CONFLUENCE_BASE_URL }}
          space-id: ${{ secrets.SPACE_ID }}
          parent-page-id: ${{ secrets.PARENT_PAGE_ID }}